import java.util.Scanner;
import java.util.concurrent.atomic.AtomicInteger;

public class Game {
    public int startGame(){
        Scanner scanner = new Scanner(System.in);

        //start game

        //create a variable to hold the user reponse using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)

        // create a variable to hold the cpu response generated by the getCPUResponse() method.

        //compare user and cpu response with each other to decide the winner.


        public int getCPUResponse(){
            // Generate random integers in range 1 to 3
        }
    }
}


